unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-a

set -g mouse on

# Usar modo Vi para navegação e cópia
set-window-option -g mode-keys vi

# Definir o comando de cópia padrão para usar wl-copy (Wayland)
set -s copy-command 'wl-copy'

# Atualizar variáveis de ambiente para o Wayland/X11
set-option -g update-environment "DISPLAY WAYLAND_DISPLAY SSH_AUTH_SOCK"

# Atalhos no estilo Vim para o modo de cópia (copy-mode-vi)
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

set -g status-position top
set -g base-index 1
set -g renumber-windows on

# Status Bar Styling (Gruvbox Material inspired)
set -g status-style 'bg=default,fg=#d4be98'
set -g status-left-length 30
set -g status-left "#[fg=#a9b665,bold]   #S #[fg=#d4be98,nobold]| "
set -g status-right "#[fg=#d4be98] %H:%M #[fg=#7c6f64]|#[fg=#ea6962] #h "
set -g window-status-current-format "#[fg=#d8a657,bold] #I:#W* "
set -g window-status-format "#[fg=#928374] #I:#W "

# Border styling
set -g pane-border-style 'fg=#3c3836'
set -g pane-active-border-style 'fg=#d8a657'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'
